name: Part-Windows-X64

on: workflow_call

jobs:
  buildWin-X64:
    name: Build on Windows
    runs-on: windows-2022
    permissions:
      contents: read
    steps:
      - name: Python Setup
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          architecture: x64

      - name: Checkout Source
        uses: actions/checkout@v7

      - name: Download Assets
        uses: actions/download-artifact@v8
        with:
          name: nw-assets
          path: novelwriter/assets

      - name: Build Setup Installer
        id: build
        run: |
          echo "BUILD_VERSION=$(python pkgutils.py version)" >> $Env:GITHUB_OUTPUT
          python pkgutils.py build-win-exe

      - name: Upload Installer Artefact
        uses: actions/upload-artifact@v7
        with:
          name: novelWriter-${{ steps.build.outputs.BUILD_VERSION }}-Win-Setup
          path: dist/*.exe
          if-no-files-found: error
          retention-days: 14
